---------------------------------------FASE 1: EDA--------------------------------------------------

In [2]:
import pandas as pd #hago las importaciones de librerias.
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
import warnings # para que no se imprimam los future warning
warnings.filterwarnings('ignore', category=FutureWarning)

In [4]:
pd.set_option('display.max_columns', None) # para que se muestren todas las columnas del dataframe al imprimirlo.

In [5]:
df_1= pd.read_csv("files/Customer Flight Activity.csv") # cargo el dataframe con el csv que me han dado.

In [6]:
df_2= pd.read_csv("files/Customer Loyalty History.csv")

In [7]:
df_1.head(5) #exploro el dataframe para ver su estructura y las columnas que tiene.

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0
2,100140,2017,1,6,0,6,1200,120.0,0,0
3,100214,2017,1,0,0,0,0,0.0,0,0
4,100272,2017,1,0,0,0,0,0.0,0,0

In [8]:
df_2.head(5) #exploro el segundo dataframe para ver su estructura y las columnas que tiene, y comprobar que la columna "Loyalty Number" es la misma en ambos dataframes, lo que me indica que podre unirlos por un "Merge"

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN

In [9]:
df_1.sample(5) # muestra 5 filas aleatorias del dataframe para ver si hay alguna fila con valores nulos o algún valor extraño.

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
10015,632435,2017,1,0,0,0,0,0.0,0,0
207843,369638,2018,1,0,0,0,0,0.0,0,0
192577,456259,2017,12,4,0,4,3256,325.0,0,0
149397,853608,2017,9,9,0,9,1863,186.0,0,0
265208,496357,2018,3,9,1,10,3340,417.5,0,0

In [10]:
df_2.sample(5) # muestra 5 filas aleatorias del segundo dataframe para ver si hay alguna fila con valores nulos o algún valor extraño.

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
7903,736518,Canada,Quebec,Montreal,H2Y 4R4,Female,Bachelor,83576.0,Single,Nova,7950.57,Standard,2012,7,NaN,NaN
4675,687589,Canada,Quebec,Montreal,H2T 9K8,Male,College,NaN,Divorced,Nova,3007.39,Standard,2012,6,NaN,NaN
1921,526349,Canada,British Columbia,West Vancouver,V6V 8Z3,Female,Bachelor,78641.0,Married,Aurora,7069.74,Standard,2012,8,NaN,NaN
4323,707974,Canada,British Columbia,Victoria,V10 6T5,Female,Bachelor,51510.0,Married,Nova,2810.46,Standard,2017,11,NaN,NaN
12824,811139,Canada,Ontario,Toronto,M1R 4K3,Male,Bachelor,94035.0,Married,Star,4475.42,Standard,2016,6,NaN,NaN

In [11]:
df_1.shape #busco el numero de filas y columnas del dataframe para tener una idea de su tamaño.

(405624, 10)

In [12]:
df_2.shape #busco el numero de filas y columnas del segundo dataframe para tener una idea de su tamaño.

(16737, 16)

In [13]:
df_2.describe(include= "str").T #busco una descripción de las columnas de tipo string para ver si hay alguna columna con valores nulos o algún valor extraño, y para tener una idea de los valores que hay en cada columna.
# compruebo que la columna Country tiene un valor unico con una alta frecuencia y que es candidata a a ser eliminada portque no aporta info relevante.

                 count unique       top   freq
Country          16737      1    Canada  16737
Province         16737     11   Ontario   5404
City             16737     29   Toronto   3351
Postal Code      16737     55   V6E 3D9    911
Gender           16737      2    Female   8410
Education        16737      5  Bachelor  10475
Marital Status   16737      3   Married   9735
Loyalty Card     16737      3      Star   7637
Enrollment Type  16737      2  Standard  15766

In [14]:
df_1.duplicated().sum() # busco si hay filas duplicadas en el dataframe para eliminarlas si las hay, ya que no aportan información relevante y pueden sesgar los resultados.

np.int64(1864)

In [15]:
df_2.duplicated().sum() #hago lo mismo en el segundo dataframe.

np.int64(0)

In [16]:
df_1[df_1.duplicated(keep=False)].value_counts() #busco los duplicados y cuantas veces se repiten

Loyalty Number  Year  Month  Flights Booked  Flights with Companions  Total Flights  Distance  Points Accumulated  Points Redeemed  Dollar Cost Points Redeemed
678205          2017  1      0               0                        0              0         0.0                 0                0                              3
                      2      0               0                        0              0         0.0                 0                0                              3
                      3      0               0                        0              0         0.0                 0                0                              3
                      4      0               0                        0              0         0.0                 0                0                              3
                      5      0               0                        0              0         0.0                 0                0                              3
                                                                                                                                                                  ..
949628          2018  12     0               0                        0              0         0.0                 0                0                              2
960050          2018  12     0               0                        0              0         0.0                 0                0                              2
971370          2018  12     0               0                        0              0         0.0                 0                0                              2
988392          2018  12     0               0                        0              0         0.0                 0                0                              2
989528          2018  12     0               0                        0              0         0.0                 0                0                              2
Name: count, Length: 1848, dtype: int64

In [17]:
df_2.isna().sum()/df_2.shape[0]*100 #busco el porcentaje de valores nulos por columna, divido el numero de valores nulos por el numero total de filas y multiplico por 100 para obtener el porcentaje

Loyalty Number         0.000000
Country                0.000000
Province               0.000000
City                   0.000000
Postal Code            0.000000
Gender                 0.000000
Education              0.000000
Salary                25.321145
Marital Status         0.000000
Loyalty Card           0.000000
CLV                    0.000000
Enrollment Type        0.000000
Enrollment Year        0.000000
Enrollment Month       0.000000
Cancellation Year     87.650117
Cancellation Month    87.650117
dtype: float64

In [18]:
df_1.isna().sum()/df_1.shape[0]*100 # busco el porcentaje de valores nulos por columna, divido el numero de valores nulos por el numero total de filas y multiplico por 100 para obtener el porcentaje

Loyalty Number                 0.0
Year                           0.0
Month                          0.0
Flights Booked                 0.0
Flights with Companions        0.0
Total Flights                  0.0
Distance                       0.0
Points Accumulated             0.0
Points Redeemed                0.0
Dollar Cost Points Redeemed    0.0
dtype: float64

In [19]:
df_1= df_1.drop_duplicates() #elimino las filas duplicadas

In [20]:
df_1.duplicated().sum() #compruebo que ya no hay filas duplicadas

np.int64(0)

In [21]:
df = pd.merge(df_1, df_2, on='Loyalty Number', how='left') # hago un merge de los dos dataframes utilizando la columna "Loyalty Number" como clave, y utilizando un left join para que se mantengan todas las filas del dataframe 1 y se añadan las columnas del dataframe 2 donde coincidan los valores de "Loyalty Number". Las filas del dataframe 1 que no tengan un valor coincidente en el dataframe 2 tendrán valores nulos en las columnas añadidas.

In [22]:
df.head(5) # compruebo que el merge se ha hecho correctamente y que se han añadido las columnas del dataframe 2 al dataframe 1.

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,100018,2017,1,3,0,3,1521,152.0,0,0,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.20,Standard,2016,8,NaN,NaN
1,100102,2017,1,10,4,14,2030,203.0,0,0,Canada,Ontario,Toronto,M1R 4K3,Male,College,NaN,Single,Nova,2887.74,Standard,2013,3,NaN,NaN
2,100140,2017,1,6,0,6,1200,120.0,0,0,Canada,British Columbia,Dawson Creek,U5I 4F1,Female,College,NaN,Divorced,Nova,2838.07,Standard,2016,7,NaN,NaN
3,100214,2017,1,0,0,0,0,0.0,0,0,Canada,British Columbia,Vancouver,V5R 1W3,Male,Bachelor,63253.0,Married,Star,4170.57,Standard,2015,8,NaN,NaN
4,100272,2017,1,0,0,0,0,0.0,0,0,Canada,Ontario,Toronto,P1L 8X8,Female,Bachelor,91163.0,Divorced,Star,6622.05,Standard,2014,1,NaN,NaN

In [23]:
df.to_csv('df_nuevo.csv', index=False) # guardo el nuevo dataframe en un csv para poder utilizarlo en el futuro sin tener que hacer el merge de nuevo.
print("DataFrame guardado como 'df_nuevo.csv'")

DataFrame guardado como 'df_nuevo.csv'

----------------------------------FASE 2: LIMPIEZA------------------------------------------

In [24]:
df[df.duplicated(keep=False)].sort_values("Loyalty Number") #busco si hay filas duplicadas en el nuevo dataframe, y las ordeno por la columna "Loyalty Number" para ver si hay filas con el mismo valor en esa columna.

Empty DataFrame
Columns: [Loyalty Number, Year, Month, Flights Booked, Flights with Companions, Total Flights, Distance, Points Accumulated, Points Redeemed, Dollar Cost Points Redeemed, Country, Province, City, Postal Code, Gender, Education, Salary, Marital Status, Loyalty Card, CLV, Enrollment Type, Enrollment Year, Enrollment Month, Cancellation Year, Cancellation Month]
Index: []

In [25]:
df.duplicated().sum() #compruebo que no hay filas duplicadas en el nuevo dataframe

np.int64(0)

In [26]:
df.drop(columns=["Country"], inplace=True) #elimino la columna Country ya que no aporta valor al esquema.

In [27]:
df.head(5) #compruebo que efectivamente la columna esta eliminada.

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,100018,2017,1,3,0,3,1521,152.0,0,0,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.20,Standard,2016,8,NaN,NaN
1,100102,2017,1,10,4,14,2030,203.0,0,0,Ontario,Toronto,M1R 4K3,Male,College,NaN,Single,Nova,2887.74,Standard,2013,3,NaN,NaN
2,100140,2017,1,6,0,6,1200,120.0,0,0,British Columbia,Dawson Creek,U5I 4F1,Female,College,NaN,Divorced,Nova,2838.07,Standard,2016,7,NaN,NaN
3,100214,2017,1,0,0,0,0,0.0,0,0,British Columbia,Vancouver,V5R 1W3,Male,Bachelor,63253.0,Married,Star,4170.57,Standard,2015,8,NaN,NaN
4,100272,2017,1,0,0,0,0,0.0,0,0,Ontario,Toronto,P1L 8X8,Female,Bachelor,91163.0,Divorced,Star,6622.05,Standard,2014,1,NaN,NaN

In [28]:
df.info() #compruebo el tipo de datos de cada columna para ver si hay que hacer alguna conversión de tipo de datos, y para tener una idea de la cantidad de valores no nulos en cada columna.

<class 'pandas.DataFrame'>
RangeIndex: 403760 entries, 0 to 403759
Data columns (total 24 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               403760 non-null  int64
 1   Year                         403760 non-null  int64
 2   Month                        403760 non-null  int64
 3   Flights Booked               403760 non-null  int64
 4   Flights with Companions      403760 non-null  int64
 5   Total Flights                403760 non-null  int64
 6   Distance                     403760 non-null  int64
 7   Points Accumulated           403760 non-null  float64
 8   Points Redeemed              403760 non-null  int64
 9   Dollar Cost Points Redeemed  403760 non-null  int64
 10  Province                     403760 non-null  str
 11  City                         403760 non-null  str
 12  Postal Code                  403760 non-null  str
 13  Gender                       403760 non-null  str
 14  Education                    403760 non-null  str
 15  Salary                       301500 non-null  float64
 16  Marital Status               403760 non-null  str
 17  Loyalty Card                 403760 non-null  str
 18  CLV                          403760 non-null  float64
 19  Enrollment Type              403760 non-null  str
 20  Enrollment Year              403760 non-null  int64
 21  Enrollment Month             403760 non-null  int64
 22  Cancellation Year            49650 non-null   float64
 23  Cancellation Month           49650 non-null   float64
dtypes: float64(5), int64(11), str(8)
memory usage: 73.9 MB