--------------------------------------- Fase 1: Exploración y Limpieza --------------------------------------------------

In [115]:
import pandas as pd #hago las importaciones de librerias.
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [116]:
import warnings # para que no se imprimam los future warning
warnings.filterwarnings('ignore', category=FutureWarning)

In [117]:
pd.set_option('display.max_columns', None) # para que se muestren todas las columnas del dataframe al imprimirlo.

In [118]:
df_1= pd.read_csv("files/Customer Flight Activity.csv") # cargo el dataframe con el csv que me han dado.

In [119]:
df_2= pd.read_csv("files/Customer Loyalty History.csv")

In [120]:
df_1.head(5) #exploro el dataframe para ver su estructura y las columnas que tiene.

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0
2,100140,2017,1,6,0,6,1200,120.0,0,0
3,100214,2017,1,0,0,0,0,0.0,0,0
4,100272,2017,1,0,0,0,0,0.0,0,0

In [121]:
df_2.head(5) #exploro el segundo dataframe para ver su estructura y las columnas que tiene, y comprobar que la columna "Loyalty Number" es la misma en ambos dataframes, lo que me indica que podre unirlos por un "Merge"

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN

In [122]:
df_1.sample(5) # muestra 5 filas aleatorias del dataframe para ver si hay alguna fila con valores nulos o algún valor extraño.

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
190124,326280,2017,12,0,0,0,0,0.0,0,0
23652,460894,2017,2,6,6,12,2184,218.0,0,0
320090,945703,2018,7,6,5,11,4829,482.0,0,0
134598,967462,2017,8,0,0,0,0,0.0,0,0
242443,618302,2018,4,3,0,3,1344,167.5,0,0

In [123]:
df_2.sample(5) # muestra 5 filas aleatorias del segundo dataframe para ver si hay alguna fila con valores nulos o algún valor extraño.

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
14673,975218,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,73049.0,Divorced,Star,7596.14,Standard,2018,7,NaN,NaN
13611,193519,Canada,Quebec,Montreal,H3T 8L4,Female,Bachelor,24287.0,Divorced,Aurora,33473.35,2018 Promotion,2018,3,NaN,NaN
2756,597981,Canada,Ontario,Toronto,M8Y 4K8,Female,Bachelor,48626.0,Married,Aurora,8789.88,Standard,2016,11,NaN,NaN
251,780631,Canada,Ontario,Toronto,M2M 7K8,Female,Bachelor,92131.0,Married,Star,4331.46,Standard,2018,11,NaN,NaN
3633,691365,Canada,Ontario,Kingston,M9K 2P4,Male,Bachelor,52040.0,Married,Aurora,15613.95,Standard,2013,7,2015.0,12.0

In [124]:
df_1.shape #busco el numero de filas y columnas del dataframe para tener una idea de su tamaño.

(405624, 10)

In [125]:
df_2.shape #busco el numero de filas y columnas del segundo dataframe para tener una idea de su tamaño.

(16737, 16)

In [126]:
df_2.describe(include= "str").T #busco una descripción de las columnas de tipo string para ver si hay alguna columna con valores nulos o algún valor extraño, y para tener una idea de los valores que hay en cada columna.
# compruebo que la columna Country tiene un valor unico con una alta frecuencia y que es candidata a a ser eliminada porque no aporta info relevante.

                 count unique       top   freq
Country          16737      1    Canada  16737
Province         16737     11   Ontario   5404
City             16737     29   Toronto   3351
Postal Code      16737     55   V6E 3D9    911
Gender           16737      2    Female   8410
Education        16737      5  Bachelor  10475
Marital Status   16737      3   Married   9735
Loyalty Card     16737      3      Star   7637
Enrollment Type  16737      2  Standard  15766

In [127]:
df_1.duplicated().sum() # busco si hay filas duplicadas en el dataframe para eliminarlas, ya que no aportan información relevante y pueden cambiar los resultados.

np.int64(1864)

In [128]:
df_2.duplicated().sum() #hago lo mismo en el segundo dataframe.

np.int64(0)

In [129]:
df_1.drop_duplicates(inplace=True) # elimino las filas duplicadas del primer dataframe.

In [130]:
df_1.duplicated().sum() # compruebo que ya no hay filas duplicadas en el primer dataframe.

np.int64(0)

In [131]:
df_2.isna().sum()/df_2.shape[0]*100 #busco el porcentaje de valores nulos por columna, divido el numero de valores nulos por el numero total de filas y multiplico por 100 para obtener el porcentaje

Loyalty Number         0.000000
Country                0.000000
Province               0.000000
City                   0.000000
Postal Code            0.000000
Gender                 0.000000
Education              0.000000
Salary                25.321145
Marital Status         0.000000
Loyalty Card           0.000000
CLV                    0.000000
Enrollment Type        0.000000
Enrollment Year        0.000000
Enrollment Month       0.000000
Cancellation Year     87.650117
Cancellation Month    87.650117
dtype: float64

In [132]:
df_1.isna().sum()/df_1.shape[0]*100 # busco el porcentaje de valores nulos por columna, divido el numero de valores nulos por el numero total de filas y multiplico por 100 para obtener el porcentaje

Loyalty Number                 0.0
Year                           0.0
Month                          0.0
Flights Booked                 0.0
Flights with Companions        0.0
Total Flights                  0.0
Distance                       0.0
Points Accumulated             0.0
Points Redeemed                0.0
Dollar Cost Points Redeemed    0.0
dtype: float64

In [133]:
df = pd.merge(df_1, df_2, on='Loyalty Number', how='left') # hago un merge de los dos dataframes utilizando la columna "Loyalty Number" como clave, y utilizando un left join para que se mantengan todas las filas del dataframe 1 y se añadan las columnas del dataframe 2 donde coincidan los valores de "Loyalty Number". Las filas del dataframe 1 que no tengan un valor coincidente en el dataframe 2 tendrán valores nulos en las columnas añadidas.

In [134]:
df.head(5) # compruebo que el merge se ha hecho correctamente y que se han añadido las columnas del dataframe 2 al dataframe 1.

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,100018,2017,1,3,0,3,1521,152.0,0,0,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.20,Standard,2016,8,NaN,NaN
1,100102,2017,1,10,4,14,2030,203.0,0,0,Canada,Ontario,Toronto,M1R 4K3,Male,College,NaN,Single,Nova,2887.74,Standard,2013,3,NaN,NaN
2,100140,2017,1,6,0,6,1200,120.0,0,0,Canada,British Columbia,Dawson Creek,U5I 4F1,Female,College,NaN,Divorced,Nova,2838.07,Standard,2016,7,NaN,NaN
3,100214,2017,1,0,0,0,0,0.0,0,0,Canada,British Columbia,Vancouver,V5R 1W3,Male,Bachelor,63253.0,Married,Star,4170.57,Standard,2015,8,NaN,NaN
4,100272,2017,1,0,0,0,0,0.0,0,0,Canada,Ontario,Toronto,P1L 8X8,Female,Bachelor,91163.0,Divorced,Star,6622.05,Standard,2014,1,NaN,NaN

In [135]:
df.columns= df.columns.str.lower().str. replace(" ", "_") # elimino los espacios en blanco de los nombres de las columnas para evitar problemas a la hora de acceder a ellas.

In [136]:
df.drop(columns=["country"], inplace=True) # elimino la columna "Country" porque tiene un valor unico con una alta frecuencia y no aporta información relevante.

In [137]:
df.columns #compruebo que las modificaciones y la eliminacion de columna se han hecho correctamente.

Index(['loyalty_number', 'year', 'month', 'flights_booked',
       'flights_with_companions', 'total_flights', 'distance',
       'points_accumulated', 'points_redeemed', 'dollar_cost_points_redeemed',
       'province', 'city', 'postal_code', 'gender', 'education', 'salary',
       'marital_status', 'loyalty_card', 'clv', 'enrollment_type',
       'enrollment_year', 'enrollment_month', 'cancellation_year',
       'cancellation_month'],
      dtype='str')

In [138]:
df.to_csv('Files/df_nuevo.csv', index=False) # guardo el nuevo dataframe en un csv para poder utilizarlo en el futuro sin tener que hacer el merge de nuevo.
print("DataFrame guardado como 'df_nuevo.csv'")

DataFrame guardado como 'df_nuevo.csv'

Interpretación de la Fase 1 - Exploración y Limpieza

Tras completar la fase de preparación de datos, se han realizado las siguientes acciones críticas para garantizar un análisis estadístico fiable:

- Unificación de Datos: Se han combinado los datasets de actividad de vuelo (Customer Flight Analysis.csv) y el historial de lealtad (Customer Loyalty History.csv) mediante un left join sobre la columna loyalty_number. Esto permite cruzar el comportamiento de vuelo con el perfil demográfico de cada cliente.

- Estandarización: Se han transformado todos los nombres de las columnas a minúsculas y se han sustituido los espacios por guiones bajos para mejorar la legibilidad y evitar errores de sintaxis en el código.

- Tratamiento de Inconsistencias: Se detectaron valores negativos en la columna salary, los cuales fueron corregidos mediante su valor absoluto .(abs) al identificarse como errores de entrada de datos.

- Gestión de Valores Nulos: En la variable salary, se optó por la imputación mediante la mediana para no perder el volumen de datos de esos clientes, evitando así sesgos por valores extremos. En las columnas de Cancellation Year y Cancellation Month, los valores nulos se mantuvieron entendiendo que representan a clientes que aún mantienen su membresía activa.

- Integridad: Se verificó la ausencia de registros duplicados para asegurar que cada transacción y perfil sea único, cumpliendo con los estándares de consistencia requeridos.

Conclusión: El conjunto de datos resultante está optimizado y listo para el análisis estadístico y la visualización de las siguientes fases.