Evaluación Final mod.3
-----------------------------------------------FACE 2: ANÁLISIS ESTADÍSTICO---------------------------------------------------------

In [138]:
import pandas as pd #hago las importaciones de librerias.
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [139]:
import warnings # para que no se imprimam los future warning
warnings.filterwarnings('ignore', category=FutureWarning)

In [140]:
pd.set_option('display.max_columns', None) # para que se muestren todas las columnas del dataframe al imprimirlo.

In [141]:
df_limpio = pd.read_csv("files/df_nuevo.csv") # cargo el nuevo dataframe que he creado en la fase 1 para no tener que hacer el merge cada vez que quiera trabajar con el dataframe limpio.

In [142]:
df_limpio.head(5) # imprimo las primeras filas del nuevo dataframe para comprobar que se ha cargado correctamente y para tener una idea de como es el dataframe limpio.

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
0,100018,2017,1,3,0,3,1521,152.0,0,0,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.20,Standard,2016,8,NaN,NaN
1,100102,2017,1,10,4,14,2030,203.0,0,0,Ontario,Toronto,M1R 4K3,Male,College,NaN,Single,Nova,2887.74,Standard,2013,3,NaN,NaN
2,100140,2017,1,6,0,6,1200,120.0,0,0,British Columbia,Dawson Creek,U5I 4F1,Female,College,NaN,Divorced,Nova,2838.07,Standard,2016,7,NaN,NaN
3,100214,2017,1,0,0,0,0,0.0,0,0,British Columbia,Vancouver,V5R 1W3,Male,Bachelor,63253.0,Married,Star,4170.57,Standard,2015,8,NaN,NaN
4,100272,2017,1,0,0,0,0,0.0,0,0,Ontario,Toronto,P1L 8X8,Female,Bachelor,91163.0,Divorced,Star,6622.05,Standard,2014,1,NaN,NaN

In [143]:
df_limpio.shape # compruebo el numero de filas y columnas del nuevo dataframe para tener una idea de su tamaño.

(403760, 24)

In [144]:
df_limpio.duplicated().sum() # busco si hay filas duplicadas eliminarlas ya que no aportan información relevante y pueden cambiar los resultados.

np.int64(0)

In [145]:
df_limpio.info() # imprimo la información del dataframe para tener una idea de los tipos de datos que tengo y poder elegir cuales quiero analizar.

<class 'pandas.DataFrame'>
RangeIndex: 403760 entries, 0 to 403759
Data columns (total 24 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loyalty_number               403760 non-null  int64
 1   year                         403760 non-null  int64
 2   month                        403760 non-null  int64
 3   flights_booked               403760 non-null  int64
 4   flights_with_companions      403760 non-null  int64
 5   total_flights                403760 non-null  int64
 6   distance                     403760 non-null  int64
 7   points_accumulated           403760 non-null  float64
 8   points_redeemed              403760 non-null  int64
 9   dollar_cost_points_redeemed  403760 non-null  int64
 10  province                     403760 non-null  str
 11  city                         403760 non-null  str
 12  postal_code                  403760 non-null  str
 13  gender                       403760 non-null  str
 14  education                    403760 non-null  str
 15  salary                       301500 non-null  float64
 16  marital_status               403760 non-null  str
 17  loyalty_card                 403760 non-null  str
 18  clv                          403760 non-null  float64
 19  enrollment_type              403760 non-null  str
 20  enrollment_year              403760 non-null  int64
 21  enrollment_month             403760 non-null  int64
 22  cancellation_year            49650 non-null   float64
 23  cancellation_month           49650 non-null   float64
dtypes: float64(5), int64(11), str(8)
memory usage: 73.9 MB

In [146]:
df_limpio.isna().sum() # busco si hay valores nulos para eliminarlos o imputarlos si corresponde.

loyalty_number                      0
year                                0
month                               0
flights_booked                      0
flights_with_companions             0
total_flights                       0
distance                            0
points_accumulated                  0
points_redeemed                     0
dollar_cost_points_redeemed         0
province                            0
city                                0
postal_code                         0
gender                              0
education                           0
salary                         102260
marital_status                      0
loyalty_card                        0
clv                                 0
enrollment_type                     0
enrollment_year                     0
enrollment_month                    0
cancellation_year              354110
cancellation_month             354110
dtype: int64

Aqui puedo ver que las columnas "cancellation_year" y "cancelation_month" tienen valores nulos que corresponden a clientes que no han cancelado su suscripcion, por tanto, no se trabajaran ni modificaran. En la columna salary se imputaran por la mediana.

In [ ]:
df_limpio['salary'] = df_limpio['salary'].fillna(df_limpio['salary'].median()) # imputa los valores nulos de la columna "salary" con la mediana de esa columna, ya que es una variable numérica y la mediana es una medida de tendencia central que no se ve afectada por los valores extremos.

In [ ]:
df_limpio.isna().sum() #compruebo el cambio en la columna "salary" para asegurarme de que efectivamente ya no hay valores nulos.

loyalty_number                      0
year                                0
month                               0
flights_booked                      0
flights_with_companions             0
total_flights                       0
distance                            0
points_accumulated                  0
points_redeemed                     0
dollar_cost_points_redeemed         0
province                            0
city                                0
postal_code                         0
gender                              0
education                           0
salary                              0
marital_status                      0
loyalty_card                        0
clv                                 0
enrollment_type                     0
enrollment_year                     0
enrollment_month                    0
cancellation_year              354110
cancellation_month             354110
dtype: int64

In [149]:
df_limpio.describe(include= "all").T # busco una descripción de todas las columnas para saber los valores que contienen, y encuentro valores negativos en la columna 'salary'

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
loyalty_number,403760.0,NaN,NaN,NaN,549875.383713,258961.514684,100018.0,326699.0,550598.0,772152.0,999986.0
year,403760.0,NaN,NaN,NaN,2017.500352,0.5,2017.0,2017.0,2018.0,2018.0,2018.0
month,403760.0,NaN,NaN,NaN,6.501335,3.451982,1.0,4.0,7.0,10.0,12.0
flights_booked,403760.0,NaN,NaN,NaN,4.13405,5.230064,0.0,0.0,1.0,8.0,21.0
flights_with_companions,403760.0,NaN,NaN,NaN,1.036569,2.080472,0.0,0.0,0.0,1.0,11.0
total_flights,403760.0,NaN,NaN,NaN,5.170619,6.526858,0.0,0.0,1.0,10.0,32.0
distance,403760.0,NaN,NaN,NaN,1214.460979,1434.098521,0.0,0.0,525.0,2342.0,6293.0
points_accumulated,403760.0,NaN,NaN,NaN,124.263761,146.696179,0.0,0.0,53.0,240.0,676.5
points_redeemed,403760.0,NaN,NaN,NaN,30.838587,125.758002,0.0,0.0,0.0,0.0,876.0
dollar_cost_points_redeemed,403760.0,NaN,NaN,NaN,2.495973,10.172033,0.0,0.0,0.0,0.0,71.0
province,403760,11,Ontario,130258,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,403760,29,Toronto,80775,NaN,NaN,NaN,NaN,NaN,NaN,NaN
postal_code,403760,55,V6E 3D9,21944,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,403760,2,Female,202757,NaN,NaN,NaN,NaN,NaN,NaN,NaN
education,403760,5,Bachelor,252567,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary,403760.0,NaN,NaN,NaN,77794.787225,30335.160797,-58486.0,63901.0,73479.0,82940.0,407228.0
marital_status,403760,3,Married,234845,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loyalty_card,403760,3,Star,183745,NaN,NaN,NaN,NaN,NaN,NaN,NaN
clv,403760.0,NaN,NaN,NaN,7990.864857,6863.31716,1898.01,3981.78,5776.34,8937.12,83325.38
enrollment_type,403760,2,Standard,380419,NaN,NaN,NaN,NaN,NaN,NaN,NaN
enrollment_year,403760.0,NaN,NaN,NaN,2015.250716,1.979427,2012.0,2014.0,2015.0,2017.0,2018.0
enrollment_month,403760.0,NaN,NaN,NaN,6.667555,3.398829,1.0,4.0,7.0,10.0,12.0
cancellation_year,49650.0,NaN,NaN,NaN,2016.50435,1.380482,2013.0,2016.0,2017.0,2018.0,2018.0
cancellation_month,49650.0,NaN,NaN,NaN,6.962095,3.454362,1.0,4.0,7.0,10.0,12.0

In [150]:
df_limpio['salary'] = df_limpio['salary'].abs() # corrijo los valores negativos de la columna "salary" convirtiéndolos a su valor absoluto, ya que el salario no puede ser negativo.

In [151]:
df_limpio['salary'].min() # compruebo que ya no hay valores negativos en la columna "salary". el valor mínimo es 0, lo cual tiene sentido ya que el salario no puede ser negativo pero si puede ser 0.

np.float64(9081.0)

In [152]:
df_limpio.describe().T #vuelvo a describir el dataframe para comprobar que los cambios que he hecho han sido correctos y para confirmar las estadísticas descriptivas de las columnas numéricas.

,count,mean,std,min,25%,50%,75%,max
loyalty_number,403760.0,549875.383713,258961.514684,100018.00,326699.00,550598.00,772152.00,999986.00
year,403760.0,2017.500352,0.500000,2017.00,2017.00,2018.00,2018.00,2018.00
month,403760.0,6.501335,3.451982,1.00,4.00,7.00,10.00,12.00
flights_booked,403760.0,4.134050,5.230064,0.00,0.00,1.00,8.00,21.00
flights_with_companions,403760.0,1.036569,2.080472,0.00,0.00,0.00,1.00,11.00
total_flights,403760.0,5.170619,6.526858,0.00,0.00,1.00,10.00,32.00
distance,403760.0,1214.460979,1434.098521,0.00,0.00,525.00,2342.00,6293.00
points_accumulated,403760.0,124.263761,146.696179,0.00,0.00,53.00,240.00,676.50
points_redeemed,403760.0,30.838587,125.758002,0.00,0.00,0.00,0.00,876.00
dollar_cost_points_redeemed,403760.0,2.495973,10.172033,0.00,0.00,0.00,0.00,71.00
salary,403760.0,77879.284748,30117.567539,9081.00,63901.00,73479.00,82940.00,407228.00
clv,403760.0,7990.864857,6863.317160,1898.01,3981.78,5776.34,8937.12,83325.38
enrollment_year,403760.0,2015.250716,1.979427,2012.00,2014.00,2015.00,2017.00,2018.00
enrollment_month,403760.0,6.667555,3.398829,1.00,4.00,7.00,10.00,12.00
cancellation_year,49650.0,2016.504350,1.380482,2013.00,2016.00,2017.00,2018.00,2018.00
cancellation_month,49650.0,6.962095,3.454362,1.00,4.00,7.00,10.00,12.00